name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出源码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 包含主题子模块

      # 2. 安装 Hugo 扩展版
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.7'  # 替换为你的实际版本
          extended: true

      # 3. 构建网站
      - name: Build
        run: hugo --minify

      # 4. 使用 GitHub Pages Action 部署
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: FarsightLi/FarsightLi.github.io
          deploy_key: ${{ secrets.DEPLOY_TOKEN }}  # 你的私钥
          publish_dir: ./public                    # Hugo 的输出目录
          full_commit_message: Deploy from GitHub Actions (commit ${{ github.sha }})
          publish_branch: main                     # 用户页仓库的分支
          user_name: GitHub Actions
          user_email: actions@users.noreply.github.com
